language: java
install: skip

os: linux
dist: xenial
sudo: required

addons:
  sonarcloud:
    organization: "$SONAR_ORG"
    token: "$SONAR_TOKEN"

script:
  - gradle build --scan -s
  - sonar-scanner -X
  - gradle task uploadArchives

notifications:
  email: false

install:
  - true  

deploy:
  provider: releases
  file_glob: true
  file: "build/libs/gradletest-1.0.0-SNAPSHOT.jar" 
  api_key: "$GITHUB_TOKEN"
  skip_cleanup: true
  draft: true
  on:
    tags: true

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - '$HOME/.sonar/cache'  
