language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

script:
  - gradle build --scan -s

deploy:
  provider: releases
  file: build/libs/gradletest-1.0.0-SNAPSHOT.jar
  api_key:
    secure: "$GITHUB_TOKEN"
  skip_cleanup: true
  on:
    tags: true