language: java
install: skip

os: linux
dist: trusty
sudo: required

jdk: oraclejdk8

script:
  - gradle build --scan -s

notifications:
  email: false

before_deploy:
  - export RELEASE_JAR_FILE=$(ls build/libs/*.jar)
  - echo "Deploying $RELEASE_JAR_FILE to GitHub"

install:
  - true  

deploy:
  provider: releases
  file_glob: true
  file: "${RELEASE_JAR_FILE}"
  github-token: ${GITHUB_TOKEN} 
  skip_cleanup: true
  draft: true
  on:
    tags: true
  name: $TRAVIS_TAG
  tag_name: $TRAVIS_TAG
  body: "Generated release from Travis CI for build $TRAVIS_BUILD_NUMBER"    